test

diff --git a/.github/workflows/snake.yaml b/.github/workflows/snake.yaml
--- a/.github/workflows/snake.yaml
+++ b/.github/workflows/snake.yaml
@@ -1,14 +1,9 @@
 name: Generate GitHub Contributions Snake Animation
 
 on:
-  # Schedule the workflow to run daily at midnight UTC
   schedule:
     - cron: "0 0 * * *"
-
-  # Allow manual triggering of the workflow
   workflow_dispatch:
-
-  # Trigger the workflow on pushes to the main branch
   push:
     branches:
       - main
@@ -19,13 +14,13 @@ jobs:
     timeout-minutes: 10
 
     steps:
-      
-      # Step 1: Checkout the repository
       - name: Checkout Repository
         uses: actions/checkout@v4
 
+      - name: Clean dist directory
+        run: |
+          rm -rf dist/*  # Nettoie le répertoire dist avant de commencer
 
-      # Step 2: Generate the snake animations
       - name: Generate GitHub Contributions Snake Animations
         uses: Platane/snk@v3.2.0
         with:
@@ -37,9 +32,6 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
 
-      
-
-      # Step 3: Deploy the generated files to the 'output' branch
       - name: Deploy to Output Branch
         uses: peaceiris/actions-gh-pages@v4
         with:
@@ -47,35 +39,31 @@ jobs:
           publish_dir: ./dist
           publish_branch: output
           commit_message: "Update snake animation [skip ci]"
-          
-      # STEP TEST
-      - name: Fix permissions on files
-        run: |
-          chmod -R 777 dist
-          ls -l dist  # Optionnel : Pour afficher les fichiers et vérifier leurs permissions
 
-      # Step 4: Checkout the Output Branch
       - name: Checkout Output Branch
         uses: actions/checkout@v4
         with:
           ref: output  # Checkout the output branch
 
-      # Step 5: Copy the snake.svg file from the output branch to the main branch
-      - name: Verify if snake.svg exists
+      - name: Verify if github-snake.svg exists
         run: |
           if [ ! -f dist/github-snake.svg ]; then
-            echo "Error: snake.svg not found"
+            echo "Error: github-snake.svg not found"
             exit 1
           fi
 
-      - name: Copy snake.svg from output to main
+      - name: Force remove problematic files
+        run: |
+          git rm -f dist/github-snake-dark.svg dist/github-snake.svg dist/ocean.gif || true  # Force delete problematic files
+
+      - name: Copy github-snake.svg from output to main
         run: |
           mkdir -p dist
-          cp dist/github-snake.svg dist/
-          git config Sofiane.Wattiez "GitHub Actions"
-          git config sofiane.wattiez.developpeur@gmail.com "github-actions[bot]@users.noreply.github.com"
+          cp dist/github-snake.svg dist/  # Copy to the same directory in the main branch
+          git config user.name "GitHub Actions"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
           git add dist/github-snake.svg
-          git commit -m "Copy snake.svg from output branch"
+          git commit -m "Copy github-snake.svg from output branch"
           git push origin main  # Push to the main branch
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
